<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AfiliacionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $afiliaciones = [
            ['id' => 1, 'name' => 'ADMINISTRACION MUNICIPAL'],
            ['id' => 2, 'name' => 'AMAR'],
            ['id' => 3, 'name' => 'ARCA DEL ATLANTICO'],
            ['id' => 4, 'name' => 'AREDMAG'],
            ['id' => 5, 'name' => 'ASENRED'],
            ['id' => 6, 'name' => 'ASOCIACION COMUNITARIA BALBOA Y RED DE RADIO TV COMUNITARIA'],
            ['id' => 7, 'name' => 'ASOCIACION COMUNITARIA SANTIAGO DE TOLU'],
            ['id' => 8, 'name' => 'ASOCIACION CULTURAL MARSIS'],
            ['id' => 9, 'name' => 'ASOCIACION DE COMUNICACION SOMOS RED'],
            ['id' => 10, 'name' => 'ASOCIACION DE EMISORAS DEL CAUCA'],
            ['id' => 11, 'name' => 'ASOCIACION DE ORGANIZACIONES SOCIALES DEL NORTE DE IPIALES'],
            ['id' => 12, 'name' => 'ASOCOMUNAL'],
            ['id' => 13, 'name' => 'ASOJUNTAS'],
            ['id' => 14, 'name' => 'ASOMECO'],
            ['id' => 15, 'name' => 'ASOMECOM'],
            ['id' => 16, 'name' => 'ASOREDES'],
            ['id' => 17, 'name' => 'ASOREDES Y ASENRED'],
            ['id' => 18, 'name' => 'ASOREDES Y ECOSURA'],
            ['id' => 19, 'name' => 'ASORPAL'],
            ['id' => 20, 'name' => 'CADENA MELODIA'],
            ['id' => 21, 'name' => 'CADENA RADIAL AUTENTICA'],
            ['id' => 22, 'name' => 'CADENA RADIAL COMUNITARIA DE LA COSTA ATLANTICA'],
            ['id' => 23, 'name' => 'CADENA RADIAL LA LIBERTAD'],
            ['id' => 24, 'name' => 'CADENA RADIAL TRANSLACOSTA'],
            ['id' => 25, 'name' => 'CADENA SUPER'],
            ['id' => 26, 'name' => 'CAMPAÑA DE PAZ COLOMBIA PARA CRISTO'],
            ['id' => 27, 'name' => 'CARACOL'],
            ['id' => 28, 'name' => 'CASANARE EN RED'],
            ['id' => 29, 'name' => 'COLMUNDO RADIO'],
            ['id' => 30, 'name' => 'COMERCIAL'],
            ['id' => 31, 'name' => 'COMUNITARIA'],
            ['id' => 32, 'name' => 'CORMECOSU'],
            ['id' => 33, 'name' => 'CORPORACION DE LA COSTA ATLANTICA'],
            ['id' => 34, 'name' => 'CORPORACION PARA LA PROMOCION DE LA EDUCACION CULTURA Y DESARROLO SOCIAL DE CARAMANTA'],
            ['id' => 35, 'name' => 'DIÓCESIS DE CALDAS'],
            ['id' => 36, 'name' => 'DIOCESIS DE TIBU'],
            ['id' => 37, 'name' => 'DIOSECIS DE GIRARDOT'],
            ['id' => 38, 'name' => 'DIOSECIS DE ZIPAQUIRA'],
            ['id' => 39, 'name' => 'ECOSURA'],
            ['id' => 40, 'name' => 'EMISORAS INDIGENAS DE PASTO'],
            ['id' => 41, 'name' => 'FEDECOTER'],
            ['id' => 42, 'name' => 'FOPERCON'],
            ['id' => 43, 'name' => 'FUNADCION CASA DE LA CULTURA DE LA VEGA'],
            ['id' => 44, 'name' => 'FUNDACION ARTE Y VIDA'],
            ['id' => 45, 'name' => 'FUNDACION PARA LA EDUCACION Y COMUNICACION POPULAR CHIGUALO'],
            ['id' => 46, 'name' => 'INDEPENDIENTE'],
            ['id' => 47, 'name' => 'INRAI'],
            ['id' => 48, 'name' => 'INTERES PUBLICO'],
            ['id' => 49, 'name' => 'OLIMPICA'],
            ['id' => 50, 'name' => 'OSANA COMUNICACIONES'],
            ['id' => 51, 'name' => 'POLICIA NACIONAL'],
            ['id' => 52, 'name' => 'RADAR'],
            ['id' => 53, 'name' => 'RADIO RED PIJAO'],
            ['id' => 54, 'name' => 'RADIO SUPER'],
            ['id' => 55, 'name' => 'RADIOPOLIS'],
            ['id' => 56, 'name' => 'RCN RADIO'],
            ['id' => 57, 'name' => 'RECCO'],
            ['id' => 58, 'name' => 'RED DE EMISORAS COMUNITARIAS DEL CHOCO BARULE'],
            ['id' => 59, 'name' => 'RED DE EMISORAS DEL ATLANTICO'],
            ['id' => 60, 'name' => 'RED DE EMISORAS DEL SUCRE'],
            ['id' => 61, 'name' => 'RED DE EMISORAS DEL VALLE'],
            ['id' => 62, 'name' => 'RED DE EMISORAS UNIVERSITARIAS RV'],
            ['id' => 63, 'name' => 'RED DE LA COSTA ATLANTICA'],
            ['id' => 64, 'name' => 'RED DE MEDIOS COMUNITARIOS DEL CESAR'],
            ['id' => 65, 'name' => 'RED DE RADIO UNIVERSITARIA DE COLOMBIA'],
            ['id' => 66, 'name' => 'RED DE RADIOS DE LA COSTA CARIBE'],
            ['id' => 67, 'name' => 'RED DE RADIOS UNIVERSITARIAS'],
            ['id' => 68, 'name' => 'RED DEL EJERCITO NACIONAL'],
            ['id' => 69, 'name' => 'RED DEL MAGDALENA'],
            ['id' => 70, 'name' => 'RED DEL TOLIMA'],
            ['id' => 71, 'name' => 'RED DEPARTAMENTAL DE EMISORAS CANTOYACO'],
            ['id' => 72, 'name' => 'RED FEDECOTER'],
            ['id' => 73, 'name' => 'RED FUNDAMER'],
            ['id' => 74, 'name' => 'RED GUACAMAYA'],
            ['id' => 75, 'name' => 'RED PIJADO DEL TOLIMA'],
            ['id' => 76, 'name' => 'RED RADIAL CAFETERA'],
            ['id' => 77, 'name' => 'RED SINDAMANOY'],
            ['id' => 78, 'name' => 'RED SONORA'],
            ['id' => 79, 'name' => 'RED VOCES Y SONIDOS DEL CAUCA'],
            ['id' => 80, 'name' => 'REDAR'],
            ['id' => 81, 'name' => 'REDBOY'],
            ['id' => 82, 'name' => 'REDE NORTE'],
            ['id' => 83, 'name' => 'REDECOM DEL VALLE'],
            ['id' => 84, 'name' => 'REDSANDER'],
            ['id' => 85, 'name' => 'RENCOCESAR'],
            ['id' => 86, 'name' => 'SISTEMA INRAI'],
            ['id' => 87, 'name' => 'SISTEMA RADIAL K DE COLOMBIA'],
            ['id' => 88, 'name' => 'SISTEMA SONORO DE COLOMBIA'],
            ['id' => 89, 'name' => 'SISTEMA VIDA COLOMBIA'],
            ['id' => 90, 'name' => 'SISTEMA VIDA INTERNACIONAL'],
            ['id' => 91, 'name' => 'TODALAR'],
        ];

        DB::table('tipo_afiliaciones')->insert($afiliaciones);
    }
}